# Generated by Django 5.0.3 on 2024-03-19 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_category_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
