# Generated by Django 5.0.3 on 2024-03-20 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='category',
        ),
        migrations.AddField(
            model_name='contact',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.category', verbose_name='Categoria'),
        ),
    ]
